version: '3.8'

networks:
  mynet:
    driver: bridge
services:
  mongodb:
    networks:
      - mynet
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # MongoDB 默认端口
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    networks:
      - mynet
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"  # Mongo Express Web 界面端口
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongodb:27017"
    depends_on:
      - mongodb

volumes:
  mongodb_data: